data <- c(200, 300, 400, 600, 1000)
min_max_normalized <- (data - min(data)) / (max(data) - min(data))
z_score_normalized <- (data - mean(data)) / sd(data)
cat("Min-max normalized data:", min_max_normalized, "\n")
cat("Z-score normalized data:", z_score_normalized, "\n")
